version: "3.9"
services:
  clothing-model:
    image: clothing-model-tfserve:latest
  gateway:
    image: clothing-gateway:latest
    environment:
      - TF_SERVING_HOST=clothing-model:8500
    ports:
      - "9696:9696"